---
- name: Deploy simple static website
  hosts: webservers
  become: yes

  vars:
    web_root: /var/www/html
    hello_txt_path: /tmp/hello.txt

  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy hello.txt to server
      copy:
        src: ../hello.txt
        dest: "{{ hello_txt_path }}"
        mode: '0644'

    - name: Generate index.html from hello.txt
      command: "cp {{ hello_txt_path }} {{ web_root }}/index.html"
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
