name: Update hello.txt from Issue

on:
  issues:
    types: [opened]

jobs:
  update-hello:
    if: github.event.issue.title == 'update-hello'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Update hello.txt with issue body
        run: |
          echo "${{ github.event.issue.body }}" > hello.txt
          git add hello.txt
          git commit -m "Update hello.txt from issue #${{ github.event.issue.number }}"
          git push origin main

      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            `hello.txt` was updated and committed.
            The CI/CD pipeline is now running.